### PR TITLE
Update ViewController.swift

### PR DESCRIPTION
**Pull request by i0532386223**

### CODE REVIEW

**Comment by lorenzomalferrari** [comment]
Fatal error: UnexpI am using your file with your changes but the error remains on line 25

Line:
let url = URL (string: self.urlStr)!

Mistake:
Thread 4: Fatal error: Unexpectedly found nil while unwrapping an Optional valueectedly found nil while unwrapping an Optional value

**Comment by IvanKramarchuk** [comment]
This error occurs because the URL in the variable self.urlStr is not valid. Try to check it in any validator, for example: https://formvalidation.io/guide/validators/uri/ (verification forms at the bottom of the page).
Perhaps the variable self.urlStr contains some special characters or an error in the header "http://"
It is also possible that contains a sign "\".
When swift cannot convert a string to a valid url, it returns nil. Because you are using direct conversion with the "!" sign, nil causes a critical error.

**Comment by lorenzomalferrari** [comment]
Great inspiration !!!

I checked the value I receive in a URL validation site and the string is correct.
If I take the string and put it on google it takes me to the page without problems.
But applying the string to a validation method written in Swift I get false as a result.
Perhaps the problem is that swift works in utf8 and the string I receive is in ANSI?

**Comment by IvanKramarchuk** [comment]
That's possible.
I have a suggestion.
Copy the value of the variable and add different characters in random places so that no one can get your url, but at the same time so that you can show an almost real example to me.

**Comment by lorenzomalferrari** [comment]
I managed to solve, the value was also read with the character ", that is obviously invalidated the url.
Thanks for the help

**Pull request closed without merging**
